/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
*/

def sumEvenFib(x: Int = 1, y: Int = 2, evenSum: Int = 2, max: Int): Int = {
  val z = x + y
  if (z >= max) evenSum
  else sumEvenFib(y, z, evenSum + {if (z % 2 == 0) z else 0}, max)
}

println(sumEvenFib(max = 4000000))
